<?php
if ($block->isValid()) {
    $content = $block->getContent();
	$linkId = $block->getLinkId();
	$price = $block->getPrice();
    $period = $block->getDefaultPeriod();
    $loanId = $block->getLoanId();
    $version = $block->getModuleVersion();
    $style = $block->getWebSaleElementStyle();

    echo '<div
 id="sparxpres_web_sale"
 class="sparxpres_product"
 data-link-id="'.$linkId.'"
 data-price="'.$price.'"
 data-period="'.$period.'"
 data-loan-id="'.$loanId.'"
 data-version="'.$version.'"
 '.$style.'>' . $content . '</div>';

    echo '
<script type="text/x-magento-init">
{
  "#sparxpres_web_sale": {
      "Sparxpres_Websale/js/sparxpres-websale": {}
  }
}
</script>
';

    echo '
<script type="text/javascript">
  require(["jquery"],function(jQuery){
    jQuery(document).on("click", ".swatch-option", function(e) {
      setTimeout(function () {
        const price = jQuery("#product-price-'.$block->getProductId().' > .price").text();
        if (price) {
            const priceMatch = /(\d{1,3}(\ |\.|\,)?\d{3})(\.|\,)?(\d{0,2})/;
            const matches = price.match(priceMatch);
            if (matches) {
                const _price = Math.ceil(Number(matches[1].replace(/[ ,.]/g, "") + "." + matches[4]));
                window.dispatchEvent(new CustomEvent("sparxpresRuntimeRecalculate", {detail: {price: _price}}));
            }
        }
      }, 200);
    });
  });
</script>
';
}
