<?php
if ($block->isValid()) {
    $content = $block->getContent();
    $linkId = $block->getLinkId();
    $price = $block->getPrice();
    $period = $block->getDefaultPeriod();
    $loanId = $block->getLoanId();
    $version = $block->getModuleVersion();
    $style = $block->getWebSaleElementStyle();

    echo '<div data-mage-init=\'{"Sparxpres_Websale/js/sparxpres-websale": {}}\'
 id="sparxpres_web_sale"
 class="sparxpres_cart"
 data-link-id="'.$linkId.'"
 data-price="'.$price.'"
 data-period="'.$period.'"
 data-loan-id="'.$loanId.'"
 data-version="'.$version.'"
 '.$style.'>' . $content . '</div>';

}
