<?php
if ($block->isValid()) {
    $content = $block->getDisplayContent();
    $linkId = $block->getLinkId();
    $price = $block->getPrice();
    $defaultPeriod = $block->getDefaultPeriod();
    $dynamicPeriod = $block->isDynamicPeriod() ? '1' : '0';
    $version = $block->getModuleVersion();

    echo '<div id="sparxpres_web_sale" class="sparxpres_cart" data-link-id="'.$linkId.'" data-price="'.$price.'" data-default-period="'.$defaultPeriod.'" data-dynamic-period="'.$dynamicPeriod.'" data-version="'.$version.'">' . $content . '</div>';

    echo '
<script type="text/x-magento-init">
{
  "#sparxpres_web_sale": {
      "Sparxpres_Websale/js/sparxpres-websale": {}
  },
  "#sparxpres_web_sale_init": {
      "Sparxpres_Websale/js/sparxpres-websale-slider": {}
  }
}
</script>
    ';
}
