<?php
if ($block->isValid()) {
    $content = $block->getContent();
    $linkId = $block->getLinkId();
    $price = $block->getPrice();
    $period = $block->getDefaultPeriod();
    $loanId = $block->getLoanId();
    $version = $block->getModuleVersion();
    $style = $block->getWebSaleElementStyle();

    echo '<div
 id="sparxpres_web_sale"
 class="sparxpres_cart"
 data-link-id="'.$linkId.'"
 data-price="'.$price.'"
 data-period="'.$period.'"
 data-loan-id="'.$loanId.'"
 data-version="'.$version.'"
 '.$style.'>' . $content . '</div>';

    echo '
<script type="text/x-magento-init">
{
  "#sparxpres_web_sale": {
      "Sparxpres_Websale/js/sparxpres-websale": {}
  }
}
</script>
';
}
